#!/bin/bash
set -e

systemctl daemon-reload
systemctl enable tunneld-custom.service
systemctl enable tunneld-shell.service

systemctl start tunneld-custom.service || true
systemctl start tunneld-shell.service || true
